apiVersion: v1
kind: PersistentVolume
metadata:
  name: netdata-parent-database-pv
  namespace: netdata
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/local/netdata  # Adjust as needed for your environment

