apiVersion: v1
kind: PersistentVolume
metadata:
  name: netdata-k8s-state-varlib-pv
  namespace: netdata
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/local/netdata  # Adjust as needed for your environment

